services:

  haskell-backend:
    build: ./haskell-backend
    container_name: dots-haskell
    restart: unless-stopped
    ports:
      - "3000:3000"

  prolog-backend:
    build: ./prolog-backend
    container_name: dots-prolog
    restart: unless-stopped
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    container_name: dots-frontend
    restart: unless-stopped
    ports:
      - "80:80"